# Generated by Django 5.1.5 on 2025-01-31 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('indicador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('formula_calculo', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganismoSectorial',
            fields=[
                ('id_organismo_sectorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('comuna', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id_tipo_medida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('resultado', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.medida')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('id_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.informe')),
            ],
        ),
        migrations.AddField(
            model_name='medida',
            name='id_organismo_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.organismosectorial'),
        ),
        migrations.AddField(
            model_name='medida',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
        migrations.AddField(
            model_name='medida',
            name='id_tipo_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.tipomedida'),
        ),
    ]
