# Generated by Django 5.1.5 on 2025-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='unidad_fizcalizable',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organismosectorial',
            name='sigla',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
