# Generated by Django 5.1.5 on 2025-04-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_customuser_telefono_documento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
