# Generated by Django 5.1.5 on 2025-04-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_documento_created_at_documento_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
            ],
        ),
    ]
