# Generated by Django 5.1.5 on 2025-04-05 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismosectorial',
            name='comuna',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='plan.comuna'),
            preserve_default=False,
        ),
    ]
