# Generated by Django 5.1.5 on 2025-04-06 00:52

import plan.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_organismosectorial_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este RUT registrado.'}, max_length=12, unique=True, validators=[plan.utils.validate_rut]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
