# Generated by Django 5.1.5 on 2025-04-07 01:05

import django.db.models.deletion
import plan.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_alter_customuser_rut_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, validators=[plan.utils.validate_phone]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.comuna'),
        ),
    ]
